// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4ZDbjmvU4S38BX4BaX0ffQwh7-oUMSQ',
    appId: '1:919318565310:web:7fcf220a0387bf29b829ef',
    messagingSenderId: '919318565310',
    projectId: 'hopeir-38770',
    authDomain: 'hopeir-38770.firebaseapp.com',
    storageBucket: 'hopeir-38770.firebasestorage.app',
    measurementId: 'G-DNVKKD0PLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_MmHNbotnsgrK7BrxuG7FeaTZih3zjfg',
    appId: '1:919318565310:android:0b022c7158ab7724b829ef',
    messagingSenderId: '919318565310',
    projectId: 'hopeir-38770',
    storageBucket: 'hopeir-38770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9nKB8nbQyMbx-MUzkG_x-8Z8ijffBwpk',
    appId: '1:919318565310:ios:2ef10bf569d216b8b829ef',
    messagingSenderId: '919318565310',
    projectId: 'hopeir-38770',
    storageBucket: 'hopeir-38770.firebasestorage.app',
    iosBundleId: 'com.example.projectAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9nKB8nbQyMbx-MUzkG_x-8Z8ijffBwpk',
    appId: '1:919318565310:ios:2ef10bf569d216b8b829ef',
    messagingSenderId: '919318565310',
    projectId: 'hopeir-38770',
    storageBucket: 'hopeir-38770.firebasestorage.app',
    iosBundleId: 'com.example.projectAlpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR4ZDbjmvU4S38BX4BaX0ffQwh7-oUMSQ',
    appId: '1:919318565310:web:f3f8e8e2e77d5e36b829ef',
    messagingSenderId: '919318565310',
    projectId: 'hopeir-38770',
    authDomain: 'hopeir-38770.firebaseapp.com',
    storageBucket: 'hopeir-38770.firebasestorage.app',
    measurementId: 'G-5JJVTCLWWK',
  );
}
