// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFa8-Rv_u1rBtVCpOfeLrI3gP5JU2wus',
    appId: '1:7745812834:web:ce2736ebdc006de7d2d43b',
    messagingSenderId: '7745812834',
    projectId: 'hopeir2025',
    authDomain: 'hopeir2025.firebaseapp.com',
    storageBucket: 'hopeir2025.firebasestorage.app',
    measurementId: 'G-83T7CBGKXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEze1EQrE3yoBuKiK_CDrRBY42U_FriAQ',
    appId: '1:7745812834:android:09c52cc039433d76d2d43b',
    messagingSenderId: '7745812834',
    projectId: 'hopeir2025',
    storageBucket: 'hopeir2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrRCaEKORjDTGhynNrGtRjmUUE1CWiVg',
    appId: '1:7745812834:ios:d74485446ebf7dd9d2d43b',
    messagingSenderId: '7745812834',
    projectId: 'hopeir2025',
    storageBucket: 'hopeir2025.firebasestorage.app',
    iosBundleId: 'com.hopeir.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrRCaEKORjDTGhynNrGtRjmUUE1CWiVg',
    appId: '1:7745812834:ios:5d93291e9d62b74bd2d43b',
    messagingSenderId: '7745812834',
    projectId: 'hopeir2025',
    storageBucket: 'hopeir2025.firebasestorage.app',
    iosBundleId: 'com.example.projectAlpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPFa8-Rv_u1rBtVCpOfeLrI3gP5JU2wus',
    appId: '1:7745812834:web:6b5b80c42075f05cd2d43b',
    messagingSenderId: '7745812834',
    projectId: 'hopeir2025',
    authDomain: 'hopeir2025.firebaseapp.com',
    storageBucket: 'hopeir2025.firebasestorage.app',
    measurementId: 'G-EKJ9DQ8Q1D',
  );
}
